%% Martin White November 2018

%Helper function for generateComponentHomologs.  Converts the 'spacing'
%data generated by Chris (distances between adjacent events) to positions

%Ref: XXXXXXX

function [output] = getEventPositions(input)

[mCO,nCO]   = size(input{1,1});                                             %Generate output matrices
[mSPS,nSPS] = size(input{2,1});
output{1,1} = nan(mCO,nCO);
output{2,1} = nan(mSPS,nSPS);

for i=1:mCO                                                                 %For each measured chromosome
    output{1,1}(i,1)=input{1,1}(i,1);                                       %put the SC length into the first column of the output CO matrix
    
    for j = 2:nCO
        if ~isnan(input{1,1}(i,j))                                          %If there is a CO
            output{1,1}(i,j)=sum(input{1,1}(i,2:j));                        %its position is the sum its value with the value of all previous CO sites
        end
    end
     
    for j = 1:nSPS
        if ~isnan(input{2,1}(i,j))                                          %If there is an SPS site
            output{2,1}(i,j)=sum(input{2,1}(i,1:j));                        %its position is the sum its value with the value of all previous SPS sites
        end
    end
    
end
output{3,1} = input{3,1};                                                   %Keep information on plant and cell IDs for each 
output{4,1} = input{4,1};                                                   %measured chromosome for downstream processing
end
